### ISSUE TITLE
pedis crashed under memtier_benchmark

### ISSUE THREAD

**Issue by tracymacding** [fastio/pedis#30]
coredump:

#0  0x00002aaaaec5a5f7 in raise () from /usr/lib64/libc.so.6
#1  0x00002aaaaec5bce8 in abort () from /usr/lib64/libc.so.6
#2  0x00002aaaaec53566 in __assert_fail_base () from /usr/lib64/libc.so.6
#3  0x00002aaaaec53612 in __assert_fail () from /usr/lib64/libc.so.6
#4  0x000000000087dea4 in arm_state (period=..., until=..., this=0x3000000c64d0) at /u01/jeff.dk/github/tmp/tracymacding/pedis/seastar/core/reactor.hh:1552
#5  arm (period=..., until=..., this=0x3000000c64d0) at /u01/jeff.dk/github/tmp/tracymacding/pedis/seastar/core/reactor.hh:1563
#6  arm (delta=..., this=0x3000000c64d0) at /u01/jeff.dk/github/tmp/tracymacding/pedis/seastar/core/reactor.hh:1579
#7  store::commit_log::impl::initialize (this=0x3000000c6400) at commit_log.cc:213
#8  0x000000000087f16a in store::commit_log::impl::append (this=0x3000000c6400, m=...) at commit_log.cc:262
#9  0x000000000087fa09 in store::commit_log::append (this=<optimized out>, m=...) at commit_log.cc:307
#10 0x000000000085821b in redis::database::set (this=0x30000023a410, rk=..., val=..., expired=0, flag=1) at db.cc:286
#11 0x00000000007b9b8d in __invoke_impl<seastar::future<seastar::foreign_ptr<seastar::lw_shared_ptr<seastar::scattered_message<char> > > >, seastar::future<seastar::foreign_ptr<seastar::lw_shared_ptr<seastar::scattered_message<char> > > > (redis::database::* const&)(redis::redis_key, seastar::basic_sstring<char, unsigned int, 31>, long, unsigned int), seastar::shared_ptr<redis::database>, redis::redis_key, seastar::basic_sstring<char, unsigned int, 31, true>, long, unsigned char> (__t=<unknown type in /u01/jeff.dk/github/tmp/tracymacding/pedis/build/release/pedis, CU 0x4b62a30, DIE 0x50cf2b6>, __f=<optimized out>)
    at /opt/scylladb/include/c++/7/bits/invoke.h:73

**Comment by tracymacding** [comment]
maybe we can disable commit log now~
